const errors = {
    // Users
    INVALID_USER_TYPE: 'INVALID_USER_TYPE',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    INVALID_USERNAME: 'INVALID_USERNAME',
    DUPLICATE_USERNAME: 'DUPLICATE_USERNAME',
    INVALID_ACCESS_CODE: 'INVALID_ACCESS_CODE',
    CODE_ALREADY_DELETED: 'CODE_ALREADY_DELETED',

    // Posts
    EMPTY_TITLE: 'EMPTY_TITLE',
    EMPTY_BODY: 'EMPTY_BODY',

    // Sessions
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
};

module.exports = errors;
