const errors = {
    INVALID_USER_TYPE: 'INVALID_USER_TYPE',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    DUPLICATE_USERNAME: 'DUPLICATE_USERNAME',
    INVALID_ACCESS_CODE: 'INVALID_ACCESS_CODE',
};

module.exports = errors;